# Generated by Django 4.0.6 on 2022-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
