# Generated by Django 4.0.6 on 2022-09-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0002_addproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddProduct',
        ),
    ]
