# Generated by Django 4.0.6 on 2022-09-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0004_addproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
