# Generated by Django 4.0.6 on 2022-09-30 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0005_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='status_category',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alpha characters are allowed.')]),
        ),
    ]
