# Generated by Django 4.0.6 on 2022-09-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0006_productcategory_status_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='status_category',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
