# Generated by Django 4.0.6 on 2022-09-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0007_addproduct_status_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='status_category',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='status_category',
            new_name='status',
        ),
    ]
