# Generated by Django 4.0.6 on 2022-10-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0008_rename_status_category_addproduct_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='image',
            field=models.ImageField(upload_to='product_pictures'),
        ),
    ]
