# Generated by Django 4.0.6 on 2022-10-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0009_alter_addproduct_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProduct',
            new_name='Products',
        ),
    ]
