# Generated by Django 4.0.6 on 2022-10-10 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0010_rename_addproduct_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-z ]+$', 'Only letters are allowed in Product Name')]),
        ),
    ]
