# Generated by Django 4.0.6 on 2022-10-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('he_admin', '0011_alter_products_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='applications')),
            ],
        ),
    ]
